export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_SUCCEEDED = 'FETCH_REPOS_SUCCEEDED';
export const FETCH_REPOS_FAILDED = 'FETCH_REPOS_FAILDED';
export const FETCH_REPO = 'FETCH_REPO';
export const FETCH_REPO_SUCCEEDED = 'FETCH_REPO_SUCCEEDED';
export const FETCH_REPO_FAILDED = 'FETCH_REPO_FAILDED';
